# Example of Argocd helm deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoapp-bhla-config-service-charts-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bhla-dev
    server: https://kubernetes.default.svc
  project: prj-bhla-apps-dev
  source:
    path: charts/config-service-chart
    repoURL: https://bitbucket.org/belden/bhla-config-service.git
    targetRevision: dev
    helm:
       valueFiles:
         - values-dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
