apiVersion: secrets-store.csi.x-k8s.io/v1 
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretproviderclass.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    secrets-store.csi.k8s.io/rotation-poll-interval: "60s"
spec:
  provider: {{ .Values.secretproviderclass.provider }}
  # region: {{ .Values.secretproviderclass.region }}
  secretObjects:
  {{- range .Values.secretproviderclass.secretObjects }}
    - secretName: {{ .secretName }}
      type: {{ .type }}
      data:
      {{- range .data }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
      {{- end }}
  {{- end }}
  parameters:
    objects: |
      {{- .Values.secretproviderclass.parameters.objects | nindent 10 }}